# Based on the original M3UPT project by LITUATUI.
# See: https://github.com/LITUATUI/M3UPT

name: Update EPG
on:
  schedule:
    - cron: "0 1 * * *"
      timezone: "Europe/Lisbon"
  workflow_dispatch:
  
jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v7
        
      - name: checkout iptv-org/epg repo
        uses: actions/checkout@v7
        with:
          repository: iptv-org/epg
          path: iptv-org-epg

      - name: update EPG
        run: sh epg/epg.sh

      - name: setup git config
        run: |
          git config user.name "🤖 R2-D2"
          git config user.email "r2d2@rebel-alliance.com"

      - name: commit
        run: |
          git pull
          cd epg && git add .
          git commit -m "Update EPG" --allow-empty
          git push origin main

      - name: Prepare publish folder
        run: |
          mkdir -p public/epg
          cp epg/epg-main.xml.gz public/epg/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          force_orphan: true